class initialization
initialize

	Anchor := 'a'.
	Break := 'br'.
	Division := 'div'.
	Heading1 := 'h1'.
	Heading2 := 'h2'.
	Heading3 := 'h3'.
	Heading4 := 'h4'.
	Href := 'href'.
	ListItem := 'li'.
	OrderedList := 'ol'.
	Paragraph := 'p'.
	Preformatted := 'pre'.
	Span := 'span'.
	Style := 'style'.
	Table := 'table'.
	TableBody := 'tableBody'.
	TableData := 'td'.
	TableHead := 'tableHead'.
	TableHeading := 'th'.
	TableRow := 'tr'.
	UnorderedList := 'ul'